<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.0" />
		<PackageReference Include="MD.PersianDateTime.Core" Version="2.3.5" />
		<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\app\app.csproj" />
		<ProjectReference Include="..\domain\domain.csproj" />
	</ItemGroup>

</Project>
